#!/bin/bash

IP=$(ip -o -4 addr list eth0 | perl -n -e 'if (m{inet\s([\d\.]+)\/\d+\s}xms) { print $1 }')
echo "DEMOAPP_TCOLLECTOR_IP=$IP"

echo "starting sshd"
/usr/sbin/sshd

sleep 5

echo CLOUDINSIGHT_SERVER=${CLOUDINSIGHT_SERVER} 
/opt/tester/tcollector/tcollector.py --logfile /var/log/tcollector/tcollector.log -P /tmp/tcollector.pid -H ${CLOUDINSIGHT_SERVER} > /dev/null 2>&1 &

sleep 1

java -cp .:/opt/tester/demoapp-1.0-SNAPSHOT-jar-with-dependencies.jar -Dlog4j.configuration=/opt/tester/log4j.properties -javaagent:/opt/tester/jolokia-jvm-1.3.1-agent.jar=executor=fixed,threadNr=5,host=0.0.0.0,port=7000,maxCollectionSize=0 com.cloudmon.demo.Server

# TCollector needs opentsdb address.
# We start it using ssh explicitly.
